# How we got here

captured by @peeja 2023-02-28

When we began Milestone 2, we had reason to believe that m-ld was a perfect fit for Tiki's goals: Tiki wanted to add "liveness", and m-ld excels at being "live". As we dug into details, however, we discovered that there are many kinds of "liveness", and what Tiki was most interested in didn't actually require the sophistication of m-ld's approach.

Our initial designs focused on a shared editing experience for multiple users. We knew that the most important use case was multiple individuals in a synchronous meeting, like a planning or standup meeting, editing the same ticket at the same time. We knew that users currently often solve this problem by copying values out of Tiki and into Google Docs, editing it there, and then copying it back. Thus it seemed natural that some kind of shared draft would be most useful to users. We discovered that m-ld would be a perfect fit for this design. Whereas currently only one user can open a Tracker Item at a time, locking out other users, under this model several users could open the same Tracker Item and share a view of draft data within a m-ld domain. This is analogous to copying the values into Google Docs, but seamless. Changes on one user's Tiki screen would immediately propagate to other users editing at the same time. When the group is finished editing, one user can press a Save button (just as in Tiki today) and commit those changes to the "actual" database, making the changes visible to non-editing viewers. This is analogous to copying the values back *from* Google Docs into Tiki, but again, is seamless and integrated into the application.

With this as a starting point, we began having deeper conversations about the users' true needs. What we discovered was that the shared draft we described was not necessarily valuable to users. Instead, it may well be more valuable to have an easier way to edit a *single field* and, on completion, save that change directly to the "actual" database. That is, there is (in our current understanding) no strong need for a shared draft incorporating multiple fields. The "liveness" we arrived at is then composed of two things:

1. **An easier experience editing a single field in a Tracker Item.** This is possible today, but is actually implemented by locking the entire Tracker Item while the field is edited. Two people cannot currently edit separate Tracker Item fields at the same time, though there is no intrinsic reason this should be the case.
2. **Immediate updates to values on the screen.** That is, when a value is shown on a user's screen, and then that value is changed in the database by another user (or the same user in a different window), the value should update with the new value. We determined that, while m-ld *could* be a part of this mechanism, it wouldn't provide much value, and in fact would probably be more complex than other solutions. In particular, because m-ld would not be the actual database, the actual database would still have to notify m-ld of changes. We therefore decided that Tiki would be best served by implementing data pushing within its own code directly.

One remaining aspect of "liveness" is not addressed here: **realtime multiplayer editing within a single field** (such as a large description field). This is of particular interest to Tiki, where it could also be applied to the wiki page editor. Currently, m-ld does not support operations within a single value. That is, every update to a value is represented as deleting the entire value and inserting an entire new one. However, supporting operations *within* values is of interest to m-ld and in its near-future plans. When that becomes possible, it may be that m-ld is more useful to Tiki. Until then, we've decided that using m-ld here would be the wrong tool for the job, and result in more complexity than the value is worth.